# Generated by Django 3.1.5 on 2021-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Test',
            field=models.IntegerField(default=-1),
        ),
    ]
