# Generated by Django 3.1.5 on 2021-02-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Latitude',
            field=models.FloatField(default=0.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='Longitude',
            field=models.FloatField(default=0.0, max_length=200),
            preserve_default=False,
        ),
    ]
