# Generated by Django 3.1.5 on 2021-02-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0002_auto_20210205_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bikeshareapp.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('RepairsID', models.AutoField(primary_key=True, serialize=False)),
                ('Issue', models.CharField(max_length=400)),
                ('AssignedOperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_operator', to='bikeshareapp.user')),
                ('BikeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshareapp.bike')),
                ('ReportedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='bikeshareapp.user')),
            ],
            options={
                'db_table': 'repairs',
            },
        ),
    ]
