# Generated by Django 3.1.5 on 2021-02-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0002_auto_20210205_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='OperatorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OperatorID', to='bikeshareapp.user'),
        ),
    ]
