# Generated by Django 3.1.5 on 2021-01-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0002_trip_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='Test',
        ),
    ]
