# Generated by Django 3.1.5 on 2021-02-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0003_auto_20210209_1031'),
        ('bikeshareapp', '0003_bike_operatorid'),
    ]

    operations = [
    ]
