# Generated by Django 3.1.5 on 2021-02-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0005_repairs_inprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='OperatorID',
        ),
    ]
