# Generated by Django 3.1.5 on 2021-02-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshareapp', '0006_remove_bike_operatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairs',
            name='AssignedOperator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_operator', to='bikeshareapp.user'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='PaymentMethods',
            field=models.BinaryField(default=None),
        ),
    ]
